# Generated by Django 3.0.3 on 2020-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingpieces',
            name='content',
        ),
        migrations.AddField(
            model_name='writingpieces',
            name='publications',
            field=models.CharField(default='', max_length=200),
        ),
    ]
