# Generated by Django 3.0.3 on 2020-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20201108_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingpieces',
            old_name='publications',
            new_name='publication',
        ),
        migrations.AddField(
            model_name='writingpieces',
            name='syndication',
            field=models.CharField(default='', max_length=200),
        ),
    ]
