# Generated by Django 3.0.3 on 2020-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20201114_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingpieces',
            old_name='link',
            new_name='pdf_link',
        ),
        migrations.AddField(
            model_name='writingpieces',
            name='pub_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
