# Generated by Django 3.0.3 on 2020-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_auto_20201114_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingpieces',
            name='syndication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
