# Generated by Django 3.0.3 on 2020-11-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_auto_20201114_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpieces',
            name='feature',
            field=models.IntegerField(choices=[(0, 'Do not feature'), (1, 'Feature')], default=0),
        ),
    ]
