# Generated by Django 3.0.3 on 2020-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_writingpieces_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpieces',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writingpieces',
            name='byline',
            field=models.CharField(default='Nikk Ogasa', max_length=500),
        ),
    ]
