# Generated by Django 3.0.3 on 2020-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_auto_20201121_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpieces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
    ]
