# Generated by Django 3.0.3 on 2020-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hold'), (1, 'Publish')], default=0),
        ),
    ]
