# Generated by Django 3.0.3 on 2020-09-08 00:18

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200902_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
