# Generated by Django 3.0.3 on 2020-09-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='picture',
        ),
    ]
